import type { GameState } from './types.js';

export const game: GameState = {
  state: 'intro',
  isPaused: false,
  demoMode: false,
  aiActive: false,
  isConsecutive: false,
  playTime: 0,
  timerStarted: false,
  shakeAmount: 0,
  introAnimTimer: 0,
  particles: [],
  meteors: [],
  npcs: [],
  birds: [],
  player: null,
  platforms: [],
  items: [],
  coins: [],
  flyingCoins: [],
  clouds: [],
  stars: [],
  cameraY: 0,
  highestCameraY: 0,
  highestPlayerY: 0,
  score: 0,
  scoreCoin: 0,
  totalCoins: 0,
  lastCoinY: 0,
  baseScoreY: 0,
  goalY: 0,
  startScore: 0,
  eventLog: [],
  loopCount: 0,
  endReason: null,
  lastScoreId: null,
  lastRank: null,
  lastScoreObj: null,
  allowAutoRank: false,
  clearTime: 0,
  lastUI: '',
  flockDir: 1,
  isNewRecord: false,
  personalBest: null
};

export const demoState = {
  active: false,
  phase: 'none' as 'none' | 'ranking' | 'scroll' | 'wait',
  startTime: 0,
  dist1: 0,
  dist2: 0,
  totalDist: 0,
  containerH: 0,
  fixedTop3Y: 0,
  t3H: 0,
  otH: 0,
  scrollDuration: 110000,
  calculated: false,
  gap: 8,
  headerH: 0,
  startScrollY: 0,
  fixedHeaderY: 0,
  wH: 0
};
