export const game = {
  state: 'intro' as 'intro' | 'play' | 'result' | 'loading' | 'title' | 'gameover' | 'clear' | 'playing' | 'intro_anim' | 'powerup_anim' | 'powerdown_anim' | 'demo',
  isPaused: false,
  demoMode: false,
  aiActive: false,
  isConsecutive: false,
  playTime: 0,
  timerStarted: false,
  shakeAmount: 0,
  introAnimTimer: 0,
  particles: [] as any[],
  meteors: [] as any[],
  npcs: [] as any[],
  birds: [] as any[],
  player: null as any,
  platforms: [] as any[],
  items: [] as any[],
  coins: [] as any[],
  flyingCoins: [] as any[],
  clouds: [] as any[],
  stars: [] as any[],
  cameraY: 0,
  highestCameraY: 0,
  highestPlayerY: 0,
  score: 0,
  scoreCoin: 0,
  totalCoins: 0,
  lastCoinY: 0,
  baseScoreY: 0,
  goalY: 0,
  startScore: 0,
  eventLog: [] as string[],
  loopCount: 0,
  endReason: null as string | null,
  lastScoreId: null as string | null,
  lastRank: null as number | null,
  lastScoreObj: null as any,
  allowAutoRank: false,
  clearTime: 0,
  lastUI: '',
  flockDir: 1,
  isNewRecord: false,
  personalBest: null as any
};

export const demoState = {
  active: false,
  phase: 'none' as 'none' | 'ranking' | 'scroll' | 'wait',
  startTime: 0,
  dist1: 0,
  dist2: 0,
  totalDist: 0,
  containerH: 0,
  fixedTop3Y: 0,
  t3H: 0,
  otH: 0,
  scrollDuration: 110000,
  calculated: false,
  gap: 8,
  headerH: 0,
  startScrollY: 0,
  fixedHeaderY: 0,
  wH: 0
};
